module.exports = {
  snipeHandler: require("./snipeHandler"),
  snipeSettings1: require("./snipeSettings1"),
  snipeSettings2: require("./snipeSettings2"),
  snipeWallet: require("./snipeWallet"),
  snipeFirstOrFail: require("./snipeFirstOrFail"),
  snipeDegenMode: require("./snipeDegenMode"),
  snipeAntiRug: require("./snipeAntiRug"),
  snipeMaxTx: require("./snipeMaxTx"),
  snipeMinTx: require("./snipeMinTx"),
  snipePreApprove: require("./snipePreApprove"),
  snipeTxOnBlacklist: require("./snipeTxOnBlacklist"),
  snipeTokenHandler: require("./snipeTokenHandler"),
  snipeAmountHandler: require("./snipeAmountHandler"),
  snipeTipHandler: require("./snipeTipHandler"),
  snipeApproveGweiHandler: require("./snipeApproveGweiHandler"),
  snipeMinLiquidityHandler: require("./snipeMinLiquidityHandler"),
  snipeMaxLiquidityHandler: require("./snipeMaxLiquidityHandler"),
  snipeSubmit: require("./snipeSubmit"),
  snipeBuyTaxHandler: require("./snipeBuyTaxHandler"),
};
