//
require("dotenv").config();

const DATA_LAUNCHPAD = [
  {
    text: "Ethereum Mainnet",
    chain_id: 1,
    rpc_provider: process.env.ETH_RPC_PROVIDER,
    testnet_rpc: process.env.TESTNET_ETH_RPC_PROVIDER,
    usdc: process.env.ETH_USDC_ADDRESS,
    testnet_usdc: process.env.TESTNET_ETH_USDC_ADDRESS,
    usdt: process.env.ETH_USDT_ADDRESS,
    testnet_usdt: process.env.TESTNET_ETH_USDT_ADDRESS,
    factory_erc20: process.env.ETH_FACTORY_ERC20_ADDRESS,
    testnet_factory_erc20: process.env.TESTNET_ETH_FACTORY_ERC20_ADDRESS,
    factory_ito_native: process.env.ETH_FACTORY_ITO_NATIVE_ADDRESS,
    testnet_factory_ito_native: process.env.TESTNET_ETH_FACTORY_ITO_NATIVE_ADDRESS,
    factory_ito_erc20: process.env.ETH_FACTORY_ITO_ERC20_ADDRESS,
    testnet_factory_ito_erc20: process.env.TESTNET_ETH_FACTORY_ITO_ERC20_ADDRESS,
    chain_scanner: "https://etherscan.io",
  },
  {
    text: "Arbitrum",
    chain_id: 42161,
    rpc_provider: process.env.ARB_RPC_PROVIDER,
    testnet_rpc: process.env.TESTNET_ARB_RPC_PROVIDER,
    usdc: process.env.ARB_USDC_ADDRESS,
    testnet_usdc: process.env.TESTNET_ARB_USDC_ADDRESS,
    usdt: process.env.ARB_USDT_ADDRESS,
    testnet_usdt: process.env.TESTNET_ARB_USDT_ADDRESS,
    factory_erc20: process.env.ARB_FACTORY_ERC20_ADDRESS,
    testnet_factory_erc20: process.env.TESTNET_ARB_FACTORY_ERC20_ADDRESS,
    factory_ito_native: process.env.ARB_FACTORY_ITO_NATIVE_ADDRESS,
    testnet_factory_ito_native: process.env.TESTNET_ARB_FACTORY_ITO_NATIVE_ADDRESS,
    factory_ito_erc20: process.env.ARB_FACTORY_ITO_ERC20_ADDRESS,
    testnet_factory_ito_erc20: process.env.TESTNET_ARB_FACTORY_ITO_ERC20_ADDRESS,
    chain_scanner: "https://arbiscan.io",
  },
  {
    text: "Avalanche C-Chain",
    chain_id: 43114,
    rpc_provider: process.env.AVA_RPC_PROVIDER,
    testnet_rpc: process.env.TESTNET_AVA_RPC_PROVIDER,
    usdc: process.env.AVA_USDC_ADDRESS,
    testnet_usdc: process.env.TESTNET_AVA_USDC_ADDRESS,
    usdt: process.env.AVA_USDT_ADDRESS,
    testnet_usdt: process.env.TESTNET_AVA_USDT_ADDRESS,
    factory_erc20: process.env.AVA_FACTORY_ERC20_ADDRESS,
    testnet_factory_erc20: process.env.TESTNET_AVA_FACTORY_ERC20_ADDRESS,
    factory_ito_native: process.env.AVA_FACTORY_ITO_NATIVE_ADDRESS,
    testnet_factory_ito_native: process.env.TESTNET_AVA_FACTORY_ITO_NATIVE_ADDRESS,
    factory_ito_erc20: process.env.AVA_FACTORY_ITO_ERC20_ADDRESS,
    testnet_factory_ito_erc20: process.env.TESTNET_AVA_FACTORY_ITO_ERC20_ADDRESS,
    chain_scanner: "https://snowtrace.io",
  },
  {
    text: "Metis Andromeda",
    chain_id: 1088,
    rpc_provider: process.env.METIS_RPC_PROVIDER,
    testnet_rpc: process.env.TESTNET_METIS_RPC_PROVIDER,
    usdc: process.env.METIS_USDC_ADDRESS,
    testnet_usdc: process.env.TESTNET_METIS_USDC_ADDRESS,
    usdt: process.env.METIS_USDT_ADDRESS,
    testnet_usdt: process.env.TESTNET_METIS_USDT_ADDRESS,
    factory_erc20: process.env.METIS_FACTORY_ERC20_ADDRESS,
    testnet_factory_erc20: process.env.TESTNET_METIS_FACTORY_ERC20_ADDRESS,
    factory_ito_native: process.env.METIS_FACTORY_ITO_NATIVE_ADDRESS,
    testnet_factory_ito_native: process.env.TESTNET_METIS_FACTORY_ITO_NATIVE_ADDRESS,
    factory_ito_erc20: process.env.METIS_FACTORY_ITO_ERC20_ADDRESS,
    testnet_factory_ito_erc20: process.env.TESTNET_METIS_FACTORY_ITO_ERC20_ADDRESS,
    chain_scanner: "https://explorer.metis.io",
  },
  {
    text: "Solana",
    chain_id: 1399811149,
    rpc_provider: process.env.SOLANA_RPC_PROVIDER,
    testnet_rpc: process.env.TESTNET_SOLANA_RPC_PROVIDER,
    usdc: process.env.SOLANA_USDC_ADDRESS,
    testnet_usdc: process.env.TESTNET_SOLANA_USDC_ADDRESS,
    usdt: process.env.SOLANA_USDT_ADDRESS,
    testnet_usdt: process.env.TESTNET_SOLANA_USDT_ADDRESS,
    factory_erc20: process.env.SOLANA_FACTORY_ERC20_ADDRESS,
    testnet_factory_erc20: process.env.TESTNET_SOLANA_FACTORY_ERC20_ADDRESS,
    factory_ito_native: process.env.SOLANA_FACTORY_ITO_NATIVE_ADDRESS,
    testnet_factory_ito_native: process.env.TESTNET_SOLANA_FACTORY_ITO_NATIVE_ADDRESS,
    factory_ito_erc20: process.env.SOLANA_FACTORY_ITO_ERC20_ADDRESS,
    testnet_factory_ito_erc20: process.env.TESTNET_SOLANA_FACTORY_ITO_ERC20_ADDRESS,
    chain_scanner: "https://solscan.io",
  },
  {
    text: "Base Mainnet",
    chain_id: 8453,
    rpc_provider: process.env.BASE_RPC_PROVIDER,
    testnet_rpc: process.env.TESTNET_BASE_RPC_PROVIDER,
    usdc: process.env.BASE_USDC_ADDRESS,
    testnet_usdc: process.env.TESTNET_BASE_USDC_ADDRESS,
    usdt: process.env.BASE_USDT_ADDRESS,
    testnet_usdt: process.env.TESTNET_BASE_USDT_ADDRESS,
    factory_erc20: process.env.BASE_FACTORY_ERC20_ADDRESS,
    testnet_factory_erc20: process.env.TESTNET_BASE_FACTORY_ERC20_ADDRESS,
    factory_ito_native: process.env.BASE_FACTORY_ITO_NATIVE_ADDRESS,
    testnet_factory_ito_native: process.env.TESTNET_BASE_FACTORY_ITO_NATIVE_ADDRESS,
    factory_ito_erc20: process.env.BASE_FACTORY_ITO_ERC20_ADDRESS,
    testnet_factory_ito_erc20: process.env.TESTNET_BASE_FACTORY_ITO_ERC20_ADDRESS,
    chain_scanner: "https://basescan.org",
  },
];

module.exports = { DATA_LAUNCHPAD };
