const TRANSFER_ETH_OPTIONS = "_transfer-eth-opts";
const TRANSFER_CUSTOM_TRANSACTION_ETH = "_customtxeth";

const TRANSFER_AMOUNT_ETH_INCLUDES = "!txeth";
const TRANSFER_AMOUNT_ETH_1 = "!txeth1";
const TRANSFER_AMOUNT_ETH_2 = "!txeth2";
const TRANSFER_AMOUNT_ETH_3 = "!txeth3";
const TRANSFER_CUSTOM_AMOUNT_ETH = "!customtxeth";
const TRANSFER_DESTINATION_WALLET_ETH_CALLBACK = "!toaddresstxeth";
const TRANSFER_PERCENT_ETH_INCLUDES = "!txpercent";
const TRANSFER_PERCENT_ETH_1 = "!txpercent1";
const TRANSFER_PERCENT_ETH_2 = "!txpercent2";
const TRANSFER_PERCENT_ETH_3 = "!txpercent3";
const TRANSFER_DESTINATION_WALLET_TOKEN_CALLBACK = "!toaddresstxtoken";
const TRANSFER_CONTINUE_ETH = "!continuetxeth";
const TRANSFER_CANCEL_ETH = "!canceltxeth";

module.exports = {
  TRANSFER_ETH_OPTIONS,
  TRANSFER_AMOUNT_ETH_INCLUDES,
  TRANSFER_AMOUNT_ETH_1,
  TRANSFER_AMOUNT_ETH_2,
  TRANSFER_AMOUNT_ETH_3,
  TRANSFER_CUSTOM_AMOUNT_ETH,
  TRANSFER_DESTINATION_WALLET_ETH_CALLBACK,
  TRANSFER_PERCENT_ETH_INCLUDES,
  TRANSFER_PERCENT_ETH_1,
  TRANSFER_PERCENT_ETH_2,
  TRANSFER_PERCENT_ETH_3,
  TRANSFER_DESTINATION_WALLET_TOKEN_CALLBACK,
  TRANSFER_CONTINUE_ETH,
  TRANSFER_CANCEL_ETH,
  TRANSFER_CUSTOM_TRANSACTION_ETH,
};
