module.exports = {
  coinGeckoCategoryHandler: require("./coinGeckoCategoryHandler"),
  coinGeckoCategoryTokensHandler: require("./coinGeckoCategoryTokensHandler"),
  coinGeckoCategoryUpdateAmountHandler: require("./coinGeckoCategoryUpdateAmountHandler"),
  coinGeckoCategoryUpdateSlippageHandler: require("./coinGeckoCategoryUpdateSlippageHandler"),
  coinGeckoCategoryUpdateNetworkHandler: require("./coinGeckoCategoryUpdateNetwork"),
  coinGeckoCategoryUpdateWalletHandler: require("./coinGeckoCategoryUpdateWalletHandler"),
  coinGeckoCategoryBuyHandler: require("./coinGeckoCategoryBuyHandler"),
  coinGeckoSelectionIncludeWallet: require("./coinGeckoSelectionIncludeWallet"),
  coinGeckoSelectionIncludeEth: require("./coinGeckoSelectionIncludeEth"),
  coinGeckoCustomAmountEthHandler: require("./coinGeckoCustomAmountEthHandler"),
  coinGeckoSelectCategoryHandler: require("./coinGeckoSelectCategoryHandler"),
  coinGeckoEnterCustomAddressHandler: require("./coinGeckoEnterCustomAddressHandler"),
  coinGeckoContinueToBuyHandler: require("./coinGeckoContinueToBuyHandler"),
  slippageCategorySelectHandler: require("./slippageCategorySelectHandler"),
  categoryCustomSlippageHandler: require("./categoryCustomSlippageHandler"),
  categorySelectionIncludeToken: require("./categorySelectionIncludeToken"),
};
